# Site settings
title: 코딩이랑 무관합니다만
email: arcuer.dev@gmail.com
explainMain : "코딩이랑 무관합니다만 페이지 입니다."
description: > # this means to ignore newlines until "baseurl:"
  코딩이랑 무관합니다만
baseurl: "/test" # the subpath of your site, e.g. /blog/
url: "https://seongjumoon.github.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  systemOutConding
discus-identifier : "comu_reply"

# Build settings
markdown: kramdown
